[klibc] stdint.h: Fix build with newer clang
Recent versions of Clang introduced definitions for __*INT64_C:
https://github.com/llvm/llvm-project/commit/33ad474c45e6d7a0de7bc75e15e27cf6cb9ff895

This results in these build errors:

usr/include/bits64/bitsize/stdint.h:27:9: error: '__INT64_C' macro redefined [-Werror,-Wmacro-redefined]
   27 | #define __INT64_C(c)  c ## L
      |         ^
<built-in>:194:9: note: previous definition is here
  194 | #define __INT64_C(c) c##L
      |         ^

Renaming these macros to something more unique avoids the errors.

Signed-off-by: Florent Revest <revest@chromium.org>
Signed-off-by: Ben Hutchings <ben@decadent.org.uk>